### ISSUE TITLE
Load DMP is broken with new save DMP

### ISSUE THREAD

**Issue by MalcolmMielle** [SchindlerReGIS/team#29]
If a DMP is saved with `save_dmp` it cannot be loaded with `load_dmp` atm because the two are not compatible

**Comment by PanchettiLorenzo** [comment]
Good point, I will fix it!

**Comment by MalcolmMielle** [comment]
No rush :). I mainly put it there so we won't forget :)

**Comment by PanchettiLorenzo** [comment]
Better do it now with fresh memory ;)
Would it be ok for you to store regression timestamp vector too in the dictionary? I see that is used several times

**Comment by MalcolmMielle** [comment]
In the PR i'm working on right now, I actually remove the `trajectory` key and added the `regression` key instead. I thinik it makes more sense: to load the DMP you need the regression so its state should have it. On the other hand, the trajectory was an unnecessary attribute of the class that was not documentated :).

The PR should be ready now (if the pipeline works). I would really appreciate if you could double check I didn't break anything :D

**Comment by PanchettiLorenzo** [comment]
Ok I thing I understand your point. We would have save_dmp that saves dmp parameters and regression, while we can save the reproduction from DmpTrajectory class save method. Did I get it correctly?
If so we need to add the timestamps vector in save_dmp as well since it is used to get the time constant of the system

**Comment by MalcolmMielle** [comment]
Exactly :)
